version: 2.1

orbs:
  sdk: ory/sdk@0.1.33
  changelog: ory/changelog@0.0.9
  goreleaser: ory/goreleaser@0.0.29
  nancy: ory/nancy@0.0.9
  docs: ory/docs@0.0.4
  golangci: ory/golangci@0.0.4

jobs:
  test:
    docker:
      - image: circleci/golang:1.14
        environment:
        - GO111MODULE=on
    working_directory: /go/src/github.com/ory/oathkeeper
    steps:
      - checkout
      - setup_remote_docker
      - run: go mod download
      - run: go install github.com/ory/go-acc github.com/mattn/goveralls
      - run: go-acc -o coverage.txt ./... -- -failfast -timeout=20m
      - run: test -z "$CIRCLE_PR_NUMBER" && goveralls -service=circle-ci -coverprofile=coverage.txt -repotoken=$COVERALLS_REPO_TOKEN || echo "forks are not allowed to push to coveralls"
      - run: ./test/e2e/run.sh
      - run: ./test/reload/run.sh

workflows:
  "test, build, and relase":
    jobs:
      - nancy/test:
        filters:
          tags:
            only: /.*/
      - golangci/lint:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - changelog/generate:
          requires:
            - test
            - golangci/lint
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - sdk/generate:
          appname: Ory_Oathkeeper
          requires:
            - test
            - golangci/lint
      - sdk/release:
          requires:
            - test
            - golangci/lint
            - goreleaser/release
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - goreleaser/test:
          filters:
            tags:
              only: /.*/
      - goreleaser/release:
          requires:
            - goreleaser/test
            - test
            - golangci/lint
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - docs/build:
          requires:
            - test
            - golangci/lint
          filters:
            tags:
              only: /.*/
            branches:
              only: master